// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a781b448-0e6f-48d9-ac99-1a0a5d02d393";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAccelXChange();
void onAccelYChange();
void onAccelZChange();
void onSoundChange();
void onPositionChange();

CloudAcceleration accel_x;
CloudAcceleration accel_y;
CloudAcceleration accel_z;
CloudElectricPotential sound;
CloudLocation position;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(accel_x, READWRITE, ON_CHANGE, onAccelXChange);
  ArduinoCloud.addProperty(accel_y, READWRITE, ON_CHANGE, onAccelYChange);
  ArduinoCloud.addProperty(accel_z, READWRITE, ON_CHANGE, onAccelZChange);
  ArduinoCloud.addProperty(sound, READWRITE, ON_CHANGE, onSoundChange);
  ArduinoCloud.addProperty(position, READWRITE, ON_CHANGE, onPositionChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
